### ISSUE TITLE
Define style sheet

### ISSUE THREAD

**Issue by cpinter** [EBATINCA/TrainUS#3]
Create QSS file based on the drawings of @dgmato that are in the presentation that can be found in SharePoint.

**Comment by dgmato** [comment]
New task: 

- [ ] Fix bug with QPushButtons. Push buttons in GUI are only clickable when the mouse is over the central part of the button. If the mouse is located next to the boundaries of the button, the button cannot be clicked. The expected behaviour is that the buttons can be clicked anywhere within the boundaries, not just the central area. See image below:

![image](https://user-images.githubusercontent.com/10816661/164705870-d965f92d-83b3-44f5-8dd5-3bd53a63d5f5.png)

@Bextia could you fix this bug?

**Comment by cpinter** [comment]
@dgmato This is not the intended use of the issue tracking system. What you described now, 6 months after the last activity on this topic, belongs to a separate ticket. The title of the ticket is "Define style sheet", which is defined. The task you are describing now is a bug in the by now existing and established style sheet. In this sense we could just have one ticket "Create TrainUs software" and add every task into that one ticket. Please create a new issue for this problem, assig it to @Bextia and once you have it, edit your comment to be empty. Thanks!

**Comment by cpinter** [comment]
I'm closing this issue becase it's done.
